name: Push branch workflow PR

on:
  push:
    branches:
      - feature/*
      - bugfix/*

jobs:
  build-branch:
    name: Build branch and run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up Java
        uses: actions/setup-java@v4.2.2
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Build and Test
        working-directory: .
        run: mvn clean install

